/** User-friendly display labels for heuristic signal IDs (replaces raw technical names) */
export const SIGNAL_DISPLAY_LABELS: Record<string, string> = {
  "file-name-pattern": "Inferred from naming",
  "router-outlet": "Template contains router outlet",
  "form-group-ngform": "Form structure detected",
  "video-audio-element": "Media elements present",
  "ngfor-list": "List-like template structure",
  "activated-route": "Uses route parameters",
  "form-builder": "Form builder usage",
  "media-player-service": "Media/player service usage",
  "many-dependencies": "High dependency usage",
  "router-usage": "Route-driven behavior detected",
  "form-group-count": "Multiple form groups",
  "service-orchestration": "High service orchestration",
  "ui-state-fields": "Multiple UI state fields",
  "orchestration-heavy": "Orchestration-heavy diagnostic",
  "template-heavy-ngfor": "Template-heavy with list",
  "mat-dialog-modal": "Dialog/modal usage",
  "modal-drawer-usage": "Modal or drawer usage",
  "heuristic_count_3+": "Multiple decomposition heuristics",
  "heuristic_count_2": "Two decomposition heuristics",
  "heuristic_count_1": "One decomposition heuristic",
  "dominant_issue_match": "Dominant issue aligns with target",
  "role_heuristic_match": "Role aligns with heuristic type",
  "line_count_1000+": "Component exceeds 1000 lines",
  "source_suffix": "Shared name suffix",
  "source_directory": "Shared directory",
  "source_prefix": "Shared name prefix",
  "source_role": "Shared component role",
  "common_signals_1": "1+ common signals",
  "common_signals_2": "2+ common signals",
  "common_signals_3": "3+ common signals",
  "common_signals_4": "4+ common signals",
  "common_signals_5": "5+ common signals",
  "dominant_issues_2+": "2+ shared dominant issues",
  "dominant_issues_1": "1 shared dominant issue",
  "line_count_consistency": "Similar line counts",
};
